### ISSUE TITLE
Suspicious notation

### ISSUE THREAD

**Issue by Alexander-Ocheretyany** [martinpilat/logic-book#42]
I've met a place with the following text: "For every theory T and sentence φ (in the same language), it
holds T, ¬φ is unsatisfiable if and only if T ⊨ φ. Why? Because by the
definitions, T, ¬φ is unsatisfiable (i.e. has no model) if ¬φ is not valid
in any model of T, which means (and here we need the assumption
that φ is a sentence) that φ is valid in every model of T and that in turn
means T ⊨ φ."

It's unclear what "T, ¬φ" means, because previously I didn't meet such notation. Does that mean that ¬φ is unsatisfiable in T? Or, maybe, I missed something? (Page 46).

**Comment by martinpilat** [comment]
It is actually the same as the union of T and ¬φ. I believe I defined this notation somewhere in propositional logic, but I will just change it to the union here. It is probably clearer.
