### ISSUE TITLE
Spare bracket

### ISSUE THREAD

**Issue by Alexander-Ocheretyany** [martinpilat/logic-book#58]
"We can easily create an algorithm that first decodes x
and y and then checks if y is indeed a tableau proof of x – axioms of
T are recursive, thus we can check if a given entry in tableau is an
axiom of T, and the atomic tableaux can also be checked recursively)."

There is a bracket at the end of the sentence. Did you want to put some part of the sentence into brackets?

**Comment by martinpilat** [comment]
Yes, I originally put the part following the - in parenthesis.

Thanks again for pointing out all the typos, they should be now fixed (once I push the new version).
